# Site settings
title: "Steercast"
description: >
  A weekly podcast about web development and design, recorded in our podcast shed. Every week we'll cover a range of topics, from the tools we use to the languages we like.
baseurl: /podcast
url: http://podcast.steer.me

collections:
  episodes:
    output: true
    permalink: /:title/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, .ruby-version, .rbenv-gemsets, .gitignore, vendor]