# Site settings
title: "Steercast"
description: >
  A weekly podcast about  development, design, and everything in between. For those of you finding your footing in the development world, Steercast brings you snippets of tips and talks to guide you through it all.
short_description: A podcast covering all things web development & design brought to you by the team at Steer
url: http://podcast.steer.me
tracker_url: http://ancient-dusk-3695.herokuapp.com/episode.mp3

collections:
  episodes:
    output: true
    permalink: /:title/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, .ruby-version, .rbenv-gemsets, .gitignore, vendor, README.markdown]
sass:
  style: compressed