# Site settings
title: "Steercast"
description: >
  A podcast covering all things web development & design, from practical coding tips to discussions about the latest web trends. Hosted by Sam Mason, Steer's lead teacher & developer, with a different member of the team as co-host each episode.
short_description: A podcast covering all things web development & design brought to you by the team at Steer
url: http://podcast.steer.me
tracker_url: http://ancient-dusk-3695.herokuapp.com/episode.mp3

collections:
  episodes:
    output: true
    permalink: /:title/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, .ruby-version, .rbenv-gemsets, .gitignore, vendor, README.markdown]
sass:
  style: compressed